SELECT
    DATE_TRUNC('MINUTE', FETCH_TS),
    COUNT(DISTINCT CASE WHEN LENGTH(BUSINESS_ID) = 2 THEN UNIQUE_ID END) AS TRAMS_CNT,
    COUNT(DISTINCT CASE WHEN LENGTH(BUSINESS_ID) != 2 THEN UNIQUE_ID END) AS BUSUS_CNT
FROM LOCATIONS.HISTORY
GROUP BY 1
ORDER BY 1
